@startuml

start
:1.създаване на мрежа;
while (2.докато има епизоди и нерешено?) is (да)
    :3.Инициализация на епизод
    __env.reset()__;

    while (4.докато има стъпки и не е край на епизод?) is (да)
      :5.Симулация на следваща стъпка:
      __nest.Simulate(STEP)__
      Избиране на действие.;
      :6.Движение на агента:
      __new_state, reward = env.step(action)__;
      if (7.има ли награда ?) then (да)
        :8.Обучение мрежа:
        __nest.Simulate(LEARN_TIME)__;
      endif
      :9.Релаксация неврони:
      __nest.Simulate(REST_TIME)__;
    endwhile (не)
endwhile (не)

:10.Запазване на резултати;

stop

@enduml
